version: '3'

services:
  nginx:
    image: nginx:1.22
    volumes:
      - ./nginx/templates/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./nginx/ssl/:/etc/ssl/
      - ./website/:/var/www/:ro  # so nginx has read-only access to static files
    environment:
      - NGINX_HOSTNAME=${NGINX_HOSTNAME}
    ports:
      - 80:80
      - 443:443
    depends_on:
      - website

  website:
    build: .
    command: gunicorn -b 0.0.0.0:8000 -w 4 --threads 2 'website:init_app()'
    restart: always
    privileged: true
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - postgres
  
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    
volumes:
  db: