"""Rename visible column

Revision ID: 424ed406979f
Revises: f38efef21f1d
Create Date: 2023-06-22 22:41:12.740182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424ed406979f'
down_revision = 'f38efef21f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('module', 'visible', new_column_name='is_visible')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('module', 'is_visible', new_column_name='visible')

    # ### end Alembic commands ###
