"""Add task hints

Revision ID: 92e8c2dc59d2
Revises: b0873d1f0461
Create Date: 2024-01-12 17:58:10.474958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92e8c2dc59d2'
down_revision = 'b0873d1f0461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hint', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('hint')

    # ### end Alembic commands ###
