"""Non-null constrains on Submission

Revision ID: b568ff80b1df
Revises: 424ed406979f
Create Date: 2023-06-28 09:43:24.304345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b568ff80b1df'
down_revision = '424ed406979f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.alter_column('time_submitted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               server_default=sa.func.now())
        batch_op.alter_column('overall_verdict',
               existing_type=postgresql.ENUM('AC', 'WA', 'TLE', 'MLE', 'RE', 'CE', 'SE', 'WJ', name='verdict'),
               nullable=False)
        batch_op.alter_column('source_code',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.alter_column('source_code',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('overall_verdict',
               existing_type=postgresql.ENUM('AC', 'WA', 'TLE', 'MLE', 'RE', 'CE', 'SE', 'WJ', name='verdict'),
               nullable=True)
        batch_op.alter_column('time_submitted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
