"""Make testcase.task_id nullable (move from `delete-orphan` to `delete` in Task-Testcase relationship)

Revision ID: be8fb79ec23d
Revises: 6b32ebcbe129
Create Date: 2023-06-09 17:45:59.668914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be8fb79ec23d'
down_revision = '6b32ebcbe129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testcase', schema=None) as batch_op:
        batch_op.alter_column('task_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testcase', schema=None) as batch_op:
        batch_op.alter_column('task_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
