"""Added module visibility

Revision ID: f38efef21f1d
Revises: be8fb79ec23d
Create Date: 2023-06-22 22:20:03.146192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f38efef21f1d'
down_revision = 'be8fb79ec23d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible', sa.BOOLEAN(), nullable=False, server_default="true"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_column('visible')

    # ### end Alembic commands ###
